[project]
name = "json-benchmark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "prettytable>=3.12.0",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
]
